repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
